import { Activity } from "./types";

/**
 * Seed tiles so the board is usable on first open rather than showing an empty
 * grid and a setup chore. All of these are editable or deletable in Settings.
 */
export const DEFAULT_ACTIVITIES: Activity[] = [
  {
    id: "act-drive",
    label: "Drive",
    glyph: "🚚",
    color: "#3b82f6",
    group: "Field",
    logMode: "punch",
    sort: 0,
    contexts: ["Job Site"],
  },
  {
    id: "act-site",
    label: "On Site",
    glyph: "🏡",
    color: "#22c55e",
    group: "Field",
    logMode: "punch",
    billable: true,
    sort: 1,
    contexts: ["Job Site"],
  },
  {
    id: "act-install",
    label: "Install",
    glyph: "🌳",
    color: "#84cc16",
    group: "Field",
    logMode: "punch",
    billable: true,
    sort: 2,
    contexts: ["Job Site"],
  },
  {
    id: "act-maint",
    label: "Maintenance",
    glyph: "✂️",
    color: "#14b8a6",
    group: "Field",
    logMode: "punch",
    billable: true,
    sort: 3,
    contexts: ["Job Site"],
  },
  {
    id: "act-walk",
    label: "Walkthrough",
    glyph: "📋",
    color: "#06b6d4",
    group: "Field",
    logMode: "punch",
    billable: true,
    sort: 4,
    contexts: ["Job Site"],
  },
  {
    id: "act-load",
    label: "Load / Unload",
    glyph: "📦",
    color: "#f97316",
    group: "Shop",
    logMode: "punch",
    sort: 5,
    contexts: ["Shop"],
  },
  {
    id: "act-equip",
    label: "Equipment",
    glyph: "🔧",
    color: "#f59e0b",
    group: "Shop",
    logMode: "punch",
    sort: 6,
    contexts: ["Shop"],
  },
  {
    id: "act-estimate",
    label: "Estimating",
    glyph: "📐",
    color: "#6366f1",
    group: "Admin",
    logMode: "punch",
    sort: 7,
    contexts: ["Office"],
  },
  {
    id: "act-calls",
    label: "Calls",
    glyph: "📞",
    color: "#a855f7",
    group: "Admin",
    logMode: "punch",
    sort: 8,
  },
  {
    id: "act-admin",
    label: "Admin",
    glyph: "💻",
    color: "#78716c",
    group: "Admin",
    logMode: "punch",
    sort: 9,
    contexts: ["Office"],
  },
  {
    id: "act-lunch",
    label: "Lunch",
    glyph: "🥪",
    color: "#ec4899",
    group: "Personal",
    logMode: "punch",
    sort: 10,
    activeFrom: "10:30",
    activeUntil: "14:30",
  },
  {
    id: "act-fuel",
    label: "Fuel",
    glyph: "⛽",
    color: "#ef4444",
    group: "Field",
    logMode: "instant",
    defaultDuration: 10,
    sort: 11,
  },
];
