// Turning taps into a proposal.
//
// The one non-obvious rule: deliveries that come with material are derived
// here rather than stored as taps. Storing them would mean a fourth tap on
// mulch has to remember to also add a delivery, and untapping has to remember
// to remove one. Deriving them makes that impossible to get wrong — the
// delivery count is a function of the material taps, always.

import { ITEMS, getItem, quantityFor } from "./catalog";
import { folderMembers } from "./layout";
import {
  SECTION_ORDER,
  type CatalogItem,
  type Estimate,
  type EstimatorSettings,
  type LineItem,
  type Section,
} from "./types";

const CATALOG_ORDER = new Map(ITEMS.map((item, i) => [item.id, i]));

function sectionFor(item: CatalogItem): Section {
  if (item.category === "labor") return "Labor";
  if (item.source === "equipment") return "Equipment";
  if (item.source === "service") return "Delivery & Debris";
  return "Materials";
}

export interface Proposal {
  lines: LineItem[];
  sections: { section: Section; lines: LineItem[]; subtotal: number }[];
  /** Delivery loads generated by material taps. */
  autoDeliveryLoads: number;
  subtotal: number;
  markup: number;
  total: number;
}

export function buildProposal(
  estimate: Estimate,
  settings: EstimatorSettings,
): Proposal {
  const autoDeliveryLoads = Object.entries(estimate.taps).reduce(
    (sum, [id, taps]) => (getItem(id)?.autoDelivery ? sum + taps : sum),
    0,
  );

  const deliveryId = settings.autoDeliveryItemId;
  const lines: LineItem[] = [];

  for (const [id, taps] of Object.entries(estimate.taps)) {
    const item = getItem(id);
    // An id with no catalog row is a stale estimate from before a sync removed
    // the item. Skip it rather than pricing a ghost.
    if (!item) continue;

    const autoLoads = id === deliveryId ? autoDeliveryLoads : 0;
    lines.push(makeLine(item, taps, autoLoads));
  }

  // The automatic deliveries still need a line when the Delivery tile itself
  // was never tapped, which is the normal case.
  if (autoDeliveryLoads > 0 && !(deliveryId in estimate.taps)) {
    const item = getItem(deliveryId);
    if (item) lines.push(makeLine(item, 0, autoDeliveryLoads));
  }

  lines.sort(
    (a, b) =>
      (CATALOG_ORDER.get(a.item.id) ?? 0) - (CATALOG_ORDER.get(b.item.id) ?? 0),
  );

  const sections = SECTION_ORDER.map((section) => {
    const inSection = lines.filter((l) => l.section === section);
    return {
      section,
      lines: inSection,
      subtotal: inSection.reduce((s, l) => s + l.total, 0),
    };
  }).filter((s) => s.lines.length > 0);

  const subtotal = lines.reduce((s, l) => s + l.total, 0);
  const markup = subtotal * (settings.markupPercent / 100);

  return {
    lines,
    sections,
    autoDeliveryLoads,
    subtotal,
    markup,
    total: subtotal + markup,
  };
}

function makeLine(
  item: CatalogItem,
  taps: number,
  autoLoads: number,
): LineItem {
  const quantity = quantityFor(item, taps + autoLoads);
  return {
    item,
    taps,
    autoLoads,
    quantity,
    total: quantity * item.costPerUnit,
    section: sectionFor(item),
  };
}

/** Running total for the unobtrusive readout on the grid. */
export function estimateTotal(
  estimate: Estimate,
  settings: EstimatorSettings,
): number {
  return buildProposal(estimate, settings).total;
}

/**
 * Taps inside a folder, for its rollup badge.
 *
 * A folder has to light up when it holds selections, or the grid stops working
 * as a checklist: a dim Equipment tile has to mean "no equipment on this job",
 * and it cannot mean that if it looks the same either way.
 */
export function folderTapCount(estimate: Estimate, folderId: string): number {
  return folderMembers(folderId).reduce(
    (sum, item) => sum + (estimate.taps[item.id] ?? 0),
    0,
  );
}
