// Quick Estimator types.
//
// The whole app is one idea: a tap is a purchase increment, not a unit. Ryan
// buys mulch by the 8-yard load and stone by the 5-ton load, so the tapping
// flow never asks "how many?" — it asks "how many loads?", and it asks that by
// counting taps.

export type ItemSource = "material" | "equipment" | "service";

export interface CatalogItem {
  /** Namespaced so a material and an equipment row can never collide. */
  id: string;
  source: ItemSource;
  name: string;
  category: string;
  unit: string;
  costPerUnit: number;

  /**
   * Units added by one tap. This is `units_per_load` where the catalog defines
   * one, and 1 otherwise — an item sold singly still has an increment, it is
   * just an increment of one.
   */
  increment: number;

  /** True when the increment came from a real load size rather than the default. */
  soldByLoad: boolean;

  /**
   * `materials.delivery_fee`. A tap on this item also books one delivery load,
   * which is why the Delivery tile means an *extra* delivery: the ones that
   * come with material are already counted.
   */
  autoDelivery: boolean;

  roundTo: number | null;

  /** Short label for the tile face; `name` is what the proposal prints. */
  tileName: string;
  glyph: string;
  color: string;
  /** Crew tiles carry their hours so a crew-day reads as a duration, not a unit. */
  hoursPerUnit?: number;
}

/** A tile is either something you add, or somewhere you go. Never both. */
export type Tile =
  | { kind: "item"; id: string; item: CatalogItem }
  | {
      kind: "folder";
      id: string;
      label: string;
      glyph: string;
      color: string;
      memberIds: string[];
    };

/**
 * The estimate in progress.
 *
 * Only manual taps are stored. Delivery lines that materials generate are
 * derived at read time, so untapping a load also removes its delivery instead
 * of leaving an orphan behind.
 */
export interface Estimate {
  jobName: string;
  taps: Record<string, number>;
  updatedAt: string;
}

export type FolderReturn = "auto" | "done";

export interface EstimatorSettings {
  /**
   * How a folder page is left. "auto" backs out after a quiet spell, "done"
   * waits for the button. The idle timer only starts after the first selection
   * on that page, so opening a folder to look never bounces you out.
   */
  folderReturn: FolderReturn;
  folderReturnDelayMs: number;
  /** Which delivery item the automatic material deliveries are priced at. */
  autoDeliveryItemId: string;
  /** Applied on the proposal screen only. 0 = show cost. */
  markupPercent: number;
}

export const DEFAULT_ESTIMATOR_SETTINGS: EstimatorSettings = {
  folderReturn: "auto",
  folderReturnDelayMs: 3000,
  autoDeliveryItemId: "svc:delivery_supplier",
  markupPercent: 0,
};

export interface LineItem {
  item: CatalogItem;
  /** Taps the user made on the tile. */
  taps: number;
  /** Delivery loads generated by material taps. Delivery lines only. */
  autoLoads: number;
  quantity: number;
  total: number;
  section: Section;
}

export type Section = "Labor" | "Materials" | "Equipment" | "Delivery & Debris";

export const SECTION_ORDER: Section[] = [
  "Labor",
  "Materials",
  "Equipment",
  "Delivery & Debris",
];
